"""
Data loader for the CICIDS2017 dataset.

CICIDS2017 is a modern IDS benchmark (2017) with realistic network traffic
and labeled attacks. It contains 2.8M+ flow records with 78 features
generated by CICFlowMeter.

Attack types:
    Benign, FTP-Patator, SSH-Patator, DoS slowloris, DoS Slowhttptest,
    DoS Hulk, DoS GoldenEye, Heartbleed, Web Attack (Brute Force, XSS,
    SQL Injection), Infiltration, Botnet, DDoS, PortScan

We group attacks into categories similar to NSL-KDD for consistency:
    - DoS: DoS slowloris, DoS Slowhttptest, DoS Hulk, DoS GoldenEye, DDoS
    - Brute Force: FTP-Patator, SSH-Patator
    - Web Attack: Web Attack Brute Force, Web Attack XSS, Web Attack SQL Injection
    - Recon: PortScan, Infiltration
    - Other: Heartbleed, Botnet

Dataset source:
    Canadian Institute for Cybersecurity, University of New Brunswick.
    Sharafaldin, Lashkari, Ghorbani. "Toward Generating a New Intrusion
    Detection Dataset and Intrusion Traffic Characterization" (ICISSP 2018).
    URL: https://www.unb.ca/cic/datasets/ids-2017.html

Author: Uvesh Patel
"""

import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
import zipfile
import urllib.request


# Hugging Face mirror — individual CSVs, no auth required
HF_BASE = "https://huggingface.co/datasets/c01dsnap/CIC-IDS2017/resolve/main"

CICIDS_FILES = [
    "Monday-WorkingHours.pcap_ISCX.csv",
    "Tuesday-WorkingHours.pcap_ISCX.csv",
    "Wednesday-workingHours.pcap_ISCX.csv",
    "Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv",
    "Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv",
    "Friday-WorkingHours-Morning.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv",
    "Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv",
]

# Attack category mapping
ATTACK_CATEGORIES = {
    'BENIGN': 'Benign',
    'FTP-Patator': 'BruteForce',
    'SSH-Patator': 'BruteForce',
    'DoS slowloris': 'DoS',
    'DoS Slowhttptest': 'DoS',
    'DoS Hulk': 'DoS',
    'DoS GoldenEye': 'DoS',
    'DDoS': 'DoS',
    'Heartbleed': 'Other',
    'Web Attack \x96 Brute Force': 'WebAttack',
    'Web Attack \x96 XSS': 'WebAttack',
    'Web Attack \x96 Sql Injection': 'WebAttack',
    'Web Attack Brute Force': 'WebAttack',
    'Web Attack XSS': 'WebAttack',
    'Web Attack Sql Injection': 'WebAttack',
    'Infiltration': 'Recon',
    'Bot': 'Other',
    'PortScan': 'Recon',
}


def download_cicids(data_dir="data"):
    """
    Download CICIDS2017 CSV files from Hugging Face (public, no auth).

    Original UNB server (205.174.165.80) is unreliable/offline as of 2025.
    Uses Hugging Face mirror: huggingface.co/datasets/c01dsnap/CIC-IDS2017
    """
    extract_dir = os.path.join(data_dir, "cicids2017")
    os.makedirs(extract_dir, exist_ok=True)

    # Check if already downloaded
    existing = [f for f in os.listdir(extract_dir) if f.endswith('.csv')]
    if len(existing) >= len(CICIDS_FILES):
        print(f"  [OK] CICIDS2017 already downloaded ({len(existing)} CSV files).")
        return extract_dir

    print(f"  Downloading CICIDS2017 from Hugging Face ({len(CICIDS_FILES)} files)...")
    for i, fname in enumerate(CICIDS_FILES):
        dest = os.path.join(extract_dir, fname)
        if os.path.exists(dest) and os.path.getsize(dest) > 1_000_000:
            print(f"    [{i+1}/{len(CICIDS_FILES)}] {fname} — already exists, skipping")
            continue

        url = f"{HF_BASE}/{fname}?download=true"
        print(f"    [{i+1}/{len(CICIDS_FILES)}] Downloading {fname}...")
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=120) as resp:
                with open(dest, 'wb') as f:
                    while True:
                        chunk = resp.read(1024 * 1024)  # 1MB chunks
                        if not chunk:
                            break
                        f.write(chunk)
            size_mb = os.path.getsize(dest) / (1024 * 1024)
            print(f"             Done ({size_mb:.1f} MB)")
        except Exception as e:
            print(f"    ERROR downloading {fname}: {e}")
            if os.path.exists(dest):
                os.remove(dest)
            raise

    print(f"  All files downloaded to {extract_dir}")
    return extract_dir


def load_cicids2017(data_dir="data", sample_fraction=0.3):
    """
    Load and combine CICIDS2017 CSV files.

    The dataset is split across multiple CSV files (one per day).
    We load all of them and combine into a single DataFrame.

    Args:
        data_dir: directory for data storage
        sample_fraction: fraction to sample (full dataset is 2.8M rows).
                        Use 0.3 for manageable size (~800k rows).

    Returns:
        df: combined DataFrame with all records
    """
    extract_dir = download_cicids(data_dir)

    # Find all CSV files
    csv_files = []
    for root, dirs, files in os.walk(extract_dir):
        for f in files:
            if f.endswith('.csv'):
                csv_files.append(os.path.join(root, f))

    if not csv_files:
        raise FileNotFoundError(f"No CSV files found in {extract_dir}")

    print(f"  Found {len(csv_files)} CSV files")

    # Load and combine
    dfs = []
    for f in sorted(csv_files):
        try:
            chunk = pd.read_csv(f, encoding='utf-8', low_memory=False)
            # Strip whitespace from column names
            chunk.columns = chunk.columns.str.strip()
            dfs.append(chunk)
            print(f"    Loaded {os.path.basename(f)}: {len(chunk)} rows")
        except Exception as e:
            print(f"    Error loading {os.path.basename(f)}: {e}")

    df = pd.concat(dfs, ignore_index=True)
    print(f"  Total: {len(df)} records")

    # Sample if needed
    if sample_fraction < 1.0:
        n_sample = int(len(df) * sample_fraction)
        df = df.sample(n=n_sample, random_state=42).reset_index(drop=True)
        print(f"  Sampled to {len(df)} records ({sample_fraction*100:.0f}%)")

    return df


def preprocess_cicids(df, test_fraction=0.3):
    """
    Preprocess CICIDS2017 data.

    Steps:
        1. Clean column names and remove invalid values (inf, NaN)
        2. Create binary labels (Benign=0, Attack=1)
        3. Create multi-class labels (attack categories)
        4. Scale numeric features
        5. Split into train/test

    Args:
        df: raw CICIDS2017 DataFrame
        test_fraction: fraction for test set

    Returns:
        dict with all processed data arrays and metadata
    """
    # Identify label column (may be 'Label' or ' Label')
    label_col = None
    for col in df.columns:
        if col.strip().lower() == 'label':
            label_col = col
            break

    if label_col is None:
        raise ValueError("Could not find label column in CICIDS2017 data")

    labels = df[label_col].str.strip()

    # Drop label and non-numeric columns
    feature_cols = [c for c in df.columns if c != label_col]
    X = df[feature_cols].copy()

    # Convert to numeric, coerce errors
    X = X.apply(pd.to_numeric, errors='coerce')

    # Replace inf with NaN, then fill NaN with 0
    X.replace([np.inf, -np.inf], np.nan, inplace=True)
    X.fillna(0, inplace=True)

    # Remove constant columns
    constant_cols = X.columns[X.std() == 0]
    X.drop(columns=constant_cols, inplace=True)
    feature_names = list(X.columns)

    print(f"  Features after cleaning: {len(feature_names)}")
    print(f"  Removed {len(constant_cols)} constant columns")

    # Create binary labels
    y_binary = (labels != 'BENIGN').astype(int).values

    # Create multi-class labels
    y_category = labels.map(lambda x: ATTACK_CATEGORIES.get(x, 'Other')).values
    le = LabelEncoder()
    y_multi = le.fit_transform(y_category)
    class_names = list(le.classes_)

    print(f"  Binary: {np.bincount(y_binary)} (benign/attack)")
    print(f"  Categories: {dict(zip(class_names, np.bincount(y_multi)))}")

    # Train/test split (stratified)
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_bin_train, y_bin_test, y_multi_train, y_multi_test = \
        train_test_split(X.values, y_binary, y_multi, test_size=test_fraction,
                         random_state=42, stratify=y_binary)

    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    print(f"  Train: {len(X_train_scaled)}, Test: {len(X_test_scaled)}")

    return {
        'X_train': X_train_scaled,
        'X_test': X_test_scaled,
        'y_train_binary': y_bin_train,
        'y_test_binary': y_bin_test,
        'y_train_multi': y_multi_train,
        'y_test_multi': y_multi_test,
        'feature_names': feature_names,
        'class_names': class_names,
        'scaler': scaler,
    }
